name: Start Building Helium for macOS

defaults:
  run:
    shell: bash

permissions:
  contents: write

on:
  workflow_call:
    inputs:
      arch:
        required: true
        type: string
      os:
        required: true
        type: string
    outputs:
      status:
        value: ${{ jobs.build_job.outputs.status }}

jobs:
  build_job:
    name: Start Building Helium for macOS
    runs-on: ${{ inputs.os }}
    outputs:
      status: ${{ steps.build.outputs.status }}
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          submodules: true
      - uses: ./.github/actions/prepare-environment
      - name: Download resources
        uses: actions/download-artifact@v4
        with:
          name: helium_macos_resources_${{ inputs.arch }}
      - name: Unpack resources
        run: ./github_unpack_resources.sh && ls -la
      - name: Prepare for building
        run: ./github_before_build.sh ${{ inputs.arch }} | tee -a github_actions_build_${{ inputs.arch }}.log

      - uses: ./.github/actions/do-build
        id: build
        with:
          arch: ${{ inputs.arch }}
          os: ${{ inputs.os }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
