name: Build macOS binaries of Helium
on:
  workflow_dispatch:
    inputs:
      runner:
        required: false
        description: "Runner image name"
        default: "macos-latest"

permissions:
  contents: write

jobs:
  build:
    name: Build macOS binaries of Helium
    strategy:
      matrix:
        arch: [arm64]
      fail-fast: true
    uses: ./.github/workflows/building.yml
    secrets: inherit
    with:
      arch: ${{ matrix.arch }}
      os: ${{ inputs.runner }}
