name: Continue building macOS binaries of Helium

defaults:
  run:
    shell: bash

permissions:
  contents: write

on:
  workflow_call:
    inputs:
      arch:
        required: true
        type: string
      os:
        required: true
        type: string
    outputs:
      status:
        value: ${{ jobs.build_job.outputs.status }}

jobs:
  build_job:
    name: Resuming Building Helium for macOS
    runs-on: ${{ inputs.os }}
    outputs:
      status: ${{ steps.build.outputs.status }}
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          submodules: true
      - uses: ./.github/actions/prepare-environment
      - name: Get previous logs
        uses: actions/download-artifact@v4
        with:
          name: github_build_logs_${{ inputs.arch }}
      - name: Download build
        uses: actions/download-artifact@v4
        with:
          name: github_build_artifact_${{ inputs.arch }}
      - name: Unpack archive of build
        run: ./github_unpack_archive.sh
      - uses: ./.github/actions/do-build
        id: build
        with:
          arch: ${{ inputs.arch }}
          os: ${{ inputs.os }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
